// <auto-generated />
using System;
using Adoption.Infrastructure.EF.Contexts.Write;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adoption.Infrastructure.EF.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20230226204816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("adoption")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adoption.Domain.Aggregates.Offert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NowePoleNowaNazwa")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(69)
                        .HasColumnType("nvarchar(69)")
                        .HasDefaultValue("wartość domyślna");

                    b.Property<int>("OffertStatus")
                        .HasColumnType("int")
                        .HasComment("Komentarz do Offert Status");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Offerts", "adoption");
                });

            modelBuilder.Entity("Adoption.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicantLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OffertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OffertId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OffertId");

                    b.HasIndex("OffertId1");

                    b.ToTable("Applications", "adoption");
                });

            modelBuilder.Entity("Adoption.Domain.Entities.Application", b =>
                {
                    b.HasOne("Adoption.Domain.Aggregates.Offert", "Offert")
                        .WithMany("Applications")
                        .HasForeignKey("OffertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Adoption.Domain.Aggregates.Offert", null)
                        .WithMany("_applications")
                        .HasForeignKey("OffertId1");

                    b.Navigation("Offert");
                });

            modelBuilder.Entity("Adoption.Domain.Aggregates.Offert", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("_applications");
                });
#pragma warning restore 612, 618
        }
    }
}
